// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRv3xJGXWTLoeJUSECV9WnydVBfEIW0G4',
    appId: '1:913072373984:web:887dd3ec6cf493c487d085',
    messagingSenderId: '913072373984',
    projectId: 'salati-007',
    authDomain: 'salati-007.firebaseapp.com',
    storageBucket: 'salati-007.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbWvgCVtnWwb4Ir8w2DioPUfu3vKvx0AE',
    appId: '1:913072373984:android:5e5bc0bf2707ee1d87d085',
    messagingSenderId: '913072373984',
    projectId: 'salati-007',
    storageBucket: 'salati-007.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEeNHeOj7DVZuwAwHH3z0ggE_UEPt-tCo',
    appId: '1:913072373984:ios:af361d2206ee157487d085',
    messagingSenderId: '913072373984',
    projectId: 'salati-007',
    storageBucket: 'salati-007.firebasestorage.app',
    iosBundleId: 'com.example.adhanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEeNHeOj7DVZuwAwHH3z0ggE_UEPt-tCo',
    appId: '1:913072373984:ios:af361d2206ee157487d085',
    messagingSenderId: '913072373984',
    projectId: 'salati-007',
    storageBucket: 'salati-007.firebasestorage.app',
    iosBundleId: 'com.example.adhanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRv3xJGXWTLoeJUSECV9WnydVBfEIW0G4',
    appId: '1:913072373984:web:7b12544f838c751787d085',
    messagingSenderId: '913072373984',
    projectId: 'salati-007',
    authDomain: 'salati-007.firebaseapp.com',
    storageBucket: 'salati-007.firebasestorage.app',
  );
}
