import 'package:flutter/material.dart';
import 'app_locale_provider.dart';

/// Simple localization strings helper
const Map<String, Map<String, String>> _strings = {
  'ar': {
    'qibla': 'القبلة',
    'home': 'الرئيسية',
    'prayerTimes': 'مواقيت الصلاة',
    'settings': 'الإعدادات',
    'currentTime': 'الوقت الآن',
    'language': 'اللغة',
    'arabic': 'العربية',
    'english': 'English',
    'french': 'Français',
    'location': 'الموقع',
    'fullScreenNotification': 'إشعار ملء الشاشة',
    'compassHaptics': 'اهتزاز البوصلة',
    'chooseTheme': 'اختيار المظهر',
    'shareApp': 'مشاركة التطبيق',
    'rateApp': 'تقييم التطبيق',
    'aboutApp': 'عن التطبيق',
    'qiblaDirection': 'جهة الشرق',
    'fajr': 'الفجر',
    'dhuhr': 'الظهر',
    'asr': 'العصر',
    'maghrib': 'المغرب',
    'isha': 'العشاء',
    'country': 'الجزائر',
    'city': 'باتنة',
    // Controls section
    'controlsTitle': 'التحكم',
    'controlsSubtitle': 'الإشعارات، الاهتزاز، المظهر',
    // Location picker
    'changeLocation': 'تغيير الموقع',
    'selectLocation': 'اختيار الموقع',
    'searchPlaceholder': 'ابحث عن مدينة أو مكان...',
    'noResults': 'لا توجد نتائج',
    'confirm': 'تأكيد',
    'cancel': 'إلغاء',
    'sunrise': 'الشروق',
    'showSunrise': 'إظهار وقت الشروق',
    'chooseCityManually': 'اختر مدينة يدوياً',
    'batteryPromptTitle': 'أذان موثوق',
    'batteryPromptBody':
        'لضمان تشغيل الأذان في وقته حتى عندما يكون التطبيق مغلقاً، اسمح لصلاتي بالعمل في الخلفية دون قيود البطارية.',
    'allow': 'السماح',
    'later': 'لاحقاً',
    'hijriCalendar': 'التقويم الهجري',
    'today': 'اليوم',
    'privacyPolicy': 'سياسة الخصوصية',
    'searchRequiresInternet': 'البحث يحتاج إنترنت',
    // Theme
    'nightMode': 'الوضع الداكن',
    'lightMode': 'الوضع الفاتح',
    'islamicMode': 'المظهر الإسلامي (أزرق)',
    'islamicGreenMode': 'المظهر الإسلامي (أخضر)',
    'islamicSpecialMode': 'الإصدار الخاص',
    // Adhan selection
    'selectAdhan': 'اختيار الأذان',
    'defaultAdhan': 'الأذان الافتراضي',
    'customAdhans': 'أذاناتي',
    'addCustomAdhan': 'إضافة أذان خاص',
    'applyToAllPrayers': 'تطبيق على كل الصلوات',
    'deleteAdhan': 'حذف الأذان',
    'fileTooLong': 'الملف طويل جداً (5 دقائق كحد أقصى)',
    'invalidFormat': 'صيغة غير مدعومة',
    'adhanAdded': 'تم إضافة الأذان',
    'adhanDeleted': 'تم حذف الأذان',
    'replayTour': 'إعادة الجولة التعريفية',
    // New controls & settings keys
    'maxVolumeAdhan': 'أقصى صوت للأذان',
    'maxVolumeAdhanDesc': 'يشغل الأذان بأعلى صوت مهما كان مستوى الصوت',
    'preAdhanReminder': 'تذكير قبل الأذان',
    'preAdhanReminderDesc': 'تنبيه قبل 15 دقيقة من وقت الصلاة',
    'liveNotificationMode': 'إشعار الصلاة الحي',
    'lnDisabled': 'معطل',
    'lnStatic': 'دائم',
    'lnDynamic': 'ديناميكي',
    'calcMethod': 'طريقة الحساب',
    'calcMethodAuto': 'تلقائي ({method})',
    'calcMethodAutoDesc': 'يتم اختياره حسب موقعك',
    'batteryOpt': 'تحسين البطارية',
    'batteryOptDesc': 'اختر "بدون قيود" لموثوقية الأذان',
    'designedBy': 'تصميم وتطوير',
    'couldNotOpenLink': 'تعذر فتح الرابط',
    // Qibla screen keys
    'qiblaDirectionSubtitle': 'اتجاه القبلة',
    'loading': 'جاري التحميل...',
    'locationNotSet': 'لم يتم تحديد الموقع',
    'locationNotSetDesc': 'اذهب إلى أوقات الصلاة واضغط "تحديث الموقع"',
    'noConnection': 'لا يوجد اتصال',
    'noConnectionDesc': 'اتصل بالإنترنت واضغط "تحديث الموقع" في أوقات الصلاة',
    'error': 'خطأ',
    'noCompassSensor': 'لا يوجد مستشعر بوصلة',
    'noCompassSensorDesc': 'هاتفك لا يدعم مستشعر البوصلة المطولب لتحديد القبلة',
    // Prayer Times & Events
    'eidGreeting': 'تقبل الله منا ومنكم',
    'ramadanGreeting': 'رمضان كريم 🌙',
    'offlineMode': 'وضع عدم الاتصال',
    'updatingLocation': 'جاري تحديث الموقع...',
    'locationUpdated': 'تم تحديث الموقع',
    'updateFailed': 'فشل التحديث - يتم استخدام البيانات المحفوظة',
    // About App
    'appFeatures': 'الميزات الرئيسية:',
    'feature1': '• مواقيت صلاة دقيقة للمدن والقرى حول العالم.',
    'feature2': '• دعم العمل بدون إنترنت باستخدام البيانات المحفوظة.',
    'feature3': '• بوصلة القبلة للاتجاه الصحيح في أي مكان.',
    'feature4': '• أذانات مخصصة وتنبيهات مسبقة الصلاة.',
    'openSourceNotice': 'هذا المشروع مفتوح المصدر ومبني باستخدام Flutter لتقديم تجربة صلاة خالية من الإعلانات تركز على الخصوصية.',
    'developedByHeart': 'طُوِّر بـ ❤️ بواسطة',
    'gotIt': 'حسناً',
    'aboutFeature1': 'مظاهر زجاجية قابلة للتخصيص',
    'aboutFeature2': 'حسابات دقيقة تلقائية للمواقيت',
    'aboutFeature3': 'إشعارات الأذان الحية في الخلفية',
    'aboutFeature4': 'بوصلة القبلة وتقويم هجري',
    'aboutFeatureOffline': 'يعمل 100% بدون إنترنت ومستقل',
    'skipTour': 'تخطي',
  },
  'en': {
    'qibla': 'Qibla',
    'home': 'Home',
    'prayerTimes': 'Prayer Times',
    'settings': 'Settings',
    'currentTime': 'Current Time',
    'language': 'Language',
    'arabic': 'العربية',
    'english': 'English',
    'french': 'Français',
    'location': 'Location',
    'fullScreenNotification': 'Full Screen Notification',
    'compassHaptics': 'Compass Haptics',
    'chooseTheme': 'Choose Theme',
    'shareApp': 'Share App',
    'rateApp': 'Rate App',
    'aboutApp': 'About App',
    'qiblaDirection': 'East Direction',
    'fajr': 'Fajr',
    'dhuhr': 'Dhuhr',
    'asr': 'Asr',
    'maghrib': 'Maghrib',
    'isha': 'Isha',
    'country': 'Algeria',
    'city': 'Batna',
    // Controls section
    'controlsTitle': 'Controls',
    'controlsSubtitle': 'Notifications, haptics, theme',
    // Location picker
    'changeLocation': 'Change location',
    'selectLocation': 'Select location',
    'searchPlaceholder': 'Search for a city or place...',
    'noResults': 'No results found',
    'confirm': 'Confirm',
    'cancel': 'Cancel',
    'sunrise': 'Sunrise',
    'showSunrise': 'Show sunrise time',
    'chooseCityManually': 'Choose city manually',
    'batteryPromptTitle': 'Reliable Adhan',
    'batteryPromptBody':
        'To make sure the adhan always plays on time — even when the app is closed — allow Salati to run in the background without battery restrictions.',
    'allow': 'Allow',
    'later': 'Later',
    'hijriCalendar': 'Hijri Calendar',
    'today': 'Today',
    'privacyPolicy': 'Privacy Policy',
    'searchRequiresInternet': 'Search requires internet',
    // Theme
    'nightMode': 'Night Mode',
    'lightMode': 'Light Mode',
    'islamicMode': 'Islamic Mode (Blue)',
    'islamicGreenMode': 'Islamic Mode (Green)',
    'islamicSpecialMode': 'Special Edition',
    // Adhan selection
    'selectAdhan': 'Select Adhan',
    'defaultAdhan': 'Default Adhan',
    'customAdhans': 'My Adhans',
    'addCustomAdhan': 'Add Custom Adhan',
    'applyToAllPrayers': 'Apply to All Prayers',
    'deleteAdhan': 'Delete Adhan',
    'fileTooLong': 'File too long (5 minutes max)',
    'invalidFormat': 'Unsupported format',
    'adhanAdded': 'Adhan added',
    'adhanDeleted': 'Adhan deleted',
    'replayTour': 'Replay Tour',
    // New controls & settings keys
    'maxVolumeAdhan': 'Max Volume Adhan',
    'maxVolumeAdhanDesc': 'Play adhan at max volume regardless of system volume',
    'preAdhanReminder': 'Pre-Adhan Reminder',
    'preAdhanReminderDesc': 'Get notified 15 minutes before prayer',
    'liveNotificationMode': 'Live Prayer Notification',
    'lnDisabled': 'Disabled',
    'lnStatic': 'Static',
    'lnDynamic': 'Dynamic',
    'calcMethod': 'Calculation Method',
    'calcMethodAuto': 'Automatic ({method})',
    'calcMethodAutoDesc': 'Automatically selected based on your location',
    'batteryOpt': 'Battery Optimization',
    'batteryOptDesc': 'Set to "Unrestricted" for Adhan reliability',
    'designedBy': 'Designed & Developed by',
    'couldNotOpenLink': 'Could not open link',
    // Qibla screen keys
    'qiblaDirectionSubtitle': 'Qibla Direction',
    'loading': 'Loading...',
    'locationNotSet': 'Location Not Set',
    'locationNotSetDesc': 'Go to Prayer Times and tap "Update Location"',
    'noConnection': 'No Connection',
    'noConnectionDesc': 'Connect to internet and tap "Update Location" in Prayer Times',
    'error': 'Error',
    'noCompassSensor': 'No Compass Sensor',
    'noCompassSensorDesc': 'Your device does not have the required compass sensor',
    // Prayer Times & Events
    'eidGreeting': 'May Allah accept from us and you',
    'ramadanGreeting': 'Ramadan Kareem 🌙',
    'offlineMode': 'Offline - using saved data',
    'updatingLocation': 'Updating location...',
    'locationUpdated': 'Location updated',
    'updateFailed': 'Update failed - using saved data',
    // About App
    'appFeatures': 'Key Features:',
    'feature1': '• Accurate prayer times for cities and villages worldwide.',
    'feature2': '• Offline support using saved local data.',
    'feature3': '• Qibla compass for accurate direction anywhere.',
    'feature4': '• Custom adhans and pre-prayer notifications.',
    'openSourceNotice': 'This project is open-source and built with Flutter to provide an ad-free, privacy-focused prayer experience.',
    'developedByHeart': 'Developed with ❤️ by',
    'gotIt': 'Got it',
    'aboutFeature1': 'Customizable Glass Themes',
    'aboutFeature2': 'Precise Auto-Calculated Times',
    'aboutFeature3': 'Live Foreground Adhans',
    'aboutFeature4': 'Qibla Compass & Hijri Dates',
    'aboutFeatureOffline': '100% Offline & Private',
    'skipTour': 'Skip',
  },
  'fr': {
    'qibla': 'Qibla',
    'home': 'Accueil',
    'prayerTimes': 'Horaires de Prière',
    'settings': 'Paramètres',
    'currentTime': 'Heure Actuelle',
    'language': 'Langue',
    'arabic': 'العربية',
    'english': 'English',
    'french': 'Français',
    'location': 'Emplacement',
    'fullScreenNotification': 'Notification Plein Écran',
    'compassHaptics': 'Vibration de la Boussole',
    'chooseTheme': 'Choisir le Thème',
    'shareApp': 'Partager l\'App',
    'rateApp': 'Évaluer l\'App',
    'aboutApp': 'À Propos',
    'qiblaDirection': 'Direction Est',
    'fajr': 'Fajr',
    'dhuhr': 'Dhuhr',
    'asr': 'Asr',
    'maghrib': 'Maghrib',
    'isha': 'Isha',
    'country': 'Algérie',
    'city': 'Batna',
    // Controls section
    'controlsTitle': 'Contrôles',
    'controlsSubtitle': 'Notifications, vibrations, thème',
    // Location picker
    'changeLocation': 'Changer l\'emplacement',
    'selectLocation': 'Sélectionner l\'emplacement',
    'searchPlaceholder': 'Rechercher une ville...',
    'noResults': 'Aucun résultat',
    'confirm': 'Confirmer',
    'cancel': 'Annuler',
    'sunrise': 'Lever du soleil',
    'showSunrise': 'Afficher le lever du soleil',
    'chooseCityManually': 'Choisir une ville manuellement',
    'batteryPromptTitle': 'Adhan fiable',
    'batteryPromptBody':
        'Pour que l\'adhan sonne toujours à l\'heure, même application fermée, autorisez Salati à fonctionner en arrière-plan sans restriction de batterie.',
    'allow': 'Autoriser',
    'later': 'Plus tard',
    'hijriCalendar': 'Calendrier hégirien',
    'today': 'Aujourd\'hui',
    'privacyPolicy': 'Politique de confidentialité',
    'searchRequiresInternet': 'La recherche nécessite Internet',
    // Theme
    'nightMode': 'Mode Nuit',
    'lightMode': 'Mode Clair',
    'islamicMode': 'Mode Islamique (Bleu)',
    'islamicGreenMode': 'Mode Islamique (Vert)',
    'islamicSpecialMode': 'Édition Spéciale',
    // Adhan selection
    'selectAdhan': 'Sélectionner l\'Adhan',
    'defaultAdhan': 'Adhan par Défaut',
    'customAdhans': 'Mes Adhans',
    'addCustomAdhan': 'Ajouter un Adhan',
    'applyToAllPrayers': 'Appliquer à Toutes les Prières',
    'deleteAdhan': 'Supprimer l\'Adhan',
    'fileTooLong': 'Fichier trop long (5 min max)',
    'invalidFormat': 'Format non supporté',
    'adhanAdded': 'Adhan ajouté',
    'adhanDeleted': 'Adhan supprimé',
    'replayTour': 'Rejouer la Visite',
    // New controls & settings keys
    'maxVolumeAdhan': 'Volume Adhan Max',
    'maxVolumeAdhanDesc': 'Jouer l\'adhan au volume max quel que soit le système',
    'preAdhanReminder': 'Rappel Pré-Adhan',
    'preAdhanReminderDesc': 'Être notifié 15 minutes avant la prière',
    'liveNotificationMode': 'Notification de Prière en Direct',
    'lnDisabled': 'Désactivée',
    'lnStatic': 'Statique',
    'lnDynamic': 'Dynamique',
    'calcMethod': 'Méthode de Calcul',
    'calcMethodAuto': 'Automatique ({method})',
    'calcMethodAutoDesc': 'Sélectionné automatiquement selon votre position',
    'batteryOpt': 'Optimisation Batterie',
    'batteryOptDesc': 'Régler sur "Non restreint" pour la fiabilité de l\'Adhan',
    'designedBy': 'Conçu et Développé par',
    'couldNotOpenLink': 'Impossible d\'ouvrir le lien',
    // Qibla screen keys
    'qiblaDirectionSubtitle': 'Direction de la Qibla',
    'loading': 'Chargement...',
    'locationNotSet': 'Position Non Définie',
    'locationNotSetDesc': 'Allez dans Horaires de Prière et "Mettre à jour"',
    'noConnection': 'Aucune Connexion',
    'noConnectionDesc': 'Connectez-vous et mettez à jour dans Horaires de Prière',
    'error': 'Erreur',
    'noCompassSensor': 'Pas de Boussole',
    'noCompassSensorDesc': 'Votre appareil n\'a pas de capteur boussole',
    // Prayer Times & Events
    'eidGreeting': 'Qu\'Allah accepte de nous et de vous',
    'ramadanGreeting': 'Bon Ramadan 🌙',
    'offlineMode': 'Hors ligne - données sauvegardées',
    'updatingLocation': 'Mise à jour de la position...',
    'locationUpdated': 'Position mise à jour',
    'updateFailed': 'Échec - utilisation des données sauvegardées',
    // About App
    'appFeatures': 'Caractéristiques Principales :',
    'feature1': '• Horaires de prière précis partout dans le monde.',
    'feature2': '• Support hors ligne avec données sauvegardées.',
    'feature3': '• Boussole Qibla pour une direction précise.',
    'feature4': '• Adhans personnalisés et rappels pré-prière.',
    'openSourceNotice': 'Ce projet est open-source et développé avec Flutter pour offrir une expérience sans publicité et respectueuse de la vie privée.',
    'developedByHeart': 'Développé avec ❤️ par',
    'gotIt': 'Compris',
    'aboutFeature1': 'Thèmes en Verre Personnalisables',
    'aboutFeature2': 'Calculs Précis Automatiques',
    'aboutFeature3': 'Adhans en Direct en Arrière-plan',
    'aboutFeature4': 'Boussole Qibla & Dates Hijri',
    'aboutFeatureOffline': '100% Hors Ligne & Privé',
    'skipTour': 'Passer',
  },
};

/// Get translated string by key
String t(BuildContext context, String key) {
  final controller = AppLocaleProvider.of(context);
  final langCode = controller.locale.languageCode;
  return _strings[langCode]?[key] ?? _strings['en']?[key] ?? key;
}

/// Get prayer name by index
String getPrayerName(BuildContext context, int index) {
  final keys = ['fajr', 'dhuhr', 'asr', 'maghrib', 'isha'];
  if (index < 0 || index >= keys.length) return '';
  return t(context, keys[index]);
}
